name: Regularly build app

# Send the app to Expo to be built each month so we can always have a binary available to download
on:
  schedule:
    - cron: '0 0 1 * *' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 3.x
          expo-username: ${{ secrets.EXPO_USERNAME }}
          expo-password: ${{ secrets.EXPO_PASSWORD }}
          expo-cache: true
      - run: expo build:ios --no-wait
        env:
          FORCE_COLOR: 1

