name: Test expo-apple-2fa

on: [push, workflow_dispatch]

jobs:
  test_two_factor:
    runs-on: macos-latest
    steps:
        - uses: jakemwood/expo-apple-2fa
          with:
            expo_arguments: '--type simulator'
            expo_apple_id: ${{ secrets.APPLE_ID }}
            expo_apple_password: ${{ secrets.APPLE_PASSWORD }}
            tfa_phone_number: ${{ secrets.TWO_FACTOR_PHONE_NUMBER }}
            app_specific_password: ${{ secrets.APP_SPECIFIC_PASSWORD }}
